### ISSUE TITLE
get_mut method

### ISSUE THREAD

**Issue by nikomatsakis** [orxfun/orx-concurrent-vec#12]
It'd be nice to have a `fn get_mut(&mut self, index: usize) -> Option<&mut T>`. Is there a reason not to support this?

Use case: in [salsa](https://github.com/salsa-rs/salsa), we take advantage of `&` vs `&mut` references to distinguish between database revisions. Deferring some operations until an `&mut` reference is available lets us give out `&`-references safely, for example.

**Comment by orxfun** [comment]
Thank you @nikomatsakis !

That is a good idea. I believe I didn't add it so far because I've been transforming it to the underlying vector back and forth.

```rust
use orx_concurrent_vec::*;

let con_vec = ConcurrentVec::new();
con_vec.extend([0, 1, 2]);

let mut vec = con_vec.into_inner();
*vec.get_mut(0).unwrap() = Some(42);
vec.push(Some(3));

let con_vec = ConcurrentVec::from(vec);
assert_eq!(con_vec.iter().copied().collect::<Vec<_>>(), [42, 1, 2, 3]);
```

But, also to answer your question, there is no reason not to have this nicer version:

```rust
use orx_concurrent_vec::*;

let mut con_vec = ConcurrentVec::new();
con_vec.extend([0, 1, 2]);

*con_vec.get_mut(0).unwrap() = 42;
con_vec.push(3);

assert_eq!(con_vec.iter().copied().collect::<Vec<_>>(), [42, 1, 2, 3]);
```

If you have time, feel free to check the corresponding changes for `get_mut` and `iter_mut` in this [PR](https://github.com/orxfun/orx-concurrent-vec/pull/13).

And thanks a lot for pointing to **salsa**. This sounds already super exciting:

> The key idea of salsa is that you define your program as a set of queries.

I will dive in and follow the development closely.

***PS**: It is amazing that you opened this issue at this point in time when I was working on the final updates for a parallel processing crate :) I may send you a reminder if you would have time and be interested to check.*

**Comment by nikomatsakis** [comment]
Ah, I see. Unfortunately transforming to the vector wouldn't work in my case, because we don't have full ownership, the user is invoking `&self` and `&mut self` methods in sequence.

Curious to hear more about what you're working on! `concurrent_vec` seems like a useful crate indeed.

**Comment by orxfun** [comment]
That's great to hear!

This issue is closed with addition of `get_mut` and `iter_mut` methods, and crate is published as [1.10.0](https://crates.io/crates/orx-concurrent-vec/1.10.0). Thanks for the recommendation.

In the meantime, I could manage to wrap up the parallel computing crate I've mentioned:
* https://crates.io/crates/orx-parallel
* https://github.com/orxfun/orx-parallel/

I would be delighted to hear your thoughts and suggestions:)

**Comment by nikomatsakis** [comment]
Regarding the new crate method, great!

Regarding the library, sounds interesting! I'm curious why the perf is improved in some cases. 

Does it support adapting arbitrary iterators? Sounds like it would. That seems cool.

**Comment by orxfun** [comment]
Hi Niko. Thanks a lot!

Yes, it supports arbitrary iterators.

Why it improves performance in certain scenarios is hard to answer for me since I know only one side deeply enough.

But empirically, I gained some expectation on when it has potential to improve performance, computations where we `collect`. Below is my attempt to explain why it could be performing well.

In orx-parallel, there are two main ways to collect results.

* When order is not mixed up.
  * For instance when we one-to-one map inputs to outputs as in `.map(m).collect()`. Indices of the outputs are exactly the same as the inputs. In this case, we can directly write to the final output, through a concurrent collection wrapper (ConcurrentOrderedBag). This might be helpful.
* When order is mixed up due to parallelism.
  * For instance, whenever we `filter` or `filter_map` or `flat_map`. In these cases, each thread collects its own outputs. One nice thing is that each thread's collection is sorted. So joining them into the final sorted collection seems to work well, with the help of a very small binary heap and with combined push-pop operations. But probably could be improved.
  * A special case is where we collect into `SplitVec<_, Recursive>`. For this SplitVec variant, append operation is basically no-ops. Its drawback is that this variant does not provide constant time random access. And of course it doesn't preserve the order (`collect_x` rather than `collect`). So this is a nice to have alternative whenever the use case allows, but not really a fair comparison to the others.

Below benchmarks are the small subset of many scenarios I tested where orx-parallel provides an improvement, not the general case.

| benchmark                   | method / input-length | 65536 | 262144 |
| --------------------------- | --------------------- | ----- | ------ |
| .map(m).collect()           | seq                   | 37    | 175    |
|                             | rayon                 | 30    | 103    |
|                             | Par::collect          | 18    | 84     |
|                             |                       |       |        |
| .map(m).filter(f).collect() | seq                   | 6.6   | 26     |
|                             | rayon                 | 5.3   | 6.1    |
|                             | Par::collect          | 1.6   | 3.6    |
|                             | Par::collect_x        | 1.5   | 3.4    |
|                             |                       |       |        |
| .flat_map(fm).collect()     | seq                   | 21    | 82     |
|                             | rayon                 | 454   | 1496   |
|                             | Par::collect          | 17    | 63     |
|                             | Par::collect_x        | 4     | 8      |

Most surprising case is the [**flat_map benchmark**](https://github.com/orxfun/orx-parallel/blob/main/benches/flatmap_heterogeneous.rs). For some reason rayon is significantly slower than sequential. I suspected if there is something wrong with the experimental setup but it is really a simple one. It might be some edge case, I am not really sure. On the other hand, Par:collect also doesn't benefit much from parallelization here. So in general, flat_map seems to have a big room for improvement.
