### ISSUE TITLE
raw pointer access

### ISSUE THREAD

**Issue by nikomatsakis** [orxfun/orx-concurrent-vec#18]
To fix #14 fully on my side, I think what would be *best* is if there were an accessor that returned a `*const`, something like `fn get_raw(&self, index) -> Option<*const T>`. The problem I'm encountering is that I get an `&T` which I put into a cache (as a raw pointer, as it happens) which is later invalidated by an `&mut T`. -- what I would prefer to get is a raw pointer (and, since the `ConcurrentVec` is pinned, I can rely on it not to change).

I'll fix it on my side for now by invalidating the `&T` cache, but invalidation isn't really needed.

**Comment by nikomatsakis** [comment]
Actually I'm not sure is such a method would suffice for me or not.

**Comment by nikomatsakis** [comment]
Side not, but if you *do* add this, best would to have a `*mut` version too!

**Comment by orxfun** [comment]
Thanks a lot for explaining @nikomatsakis. believe I understood the issue now. Sure, we can have the get_raw method, and its mut variant. I am on vacation for a couple of weeks, but will have the update shortly after.

**Comment by orxfun** [comment]
@nikomatsakis v2.4.0 of ConcurrentVec is released, which includes revisions in internal structure, extended tests and introduces the methods discussed in this issue.

`orx-concurrent-vec = "2.4.0"`

You may see the methods here:
* [get_raw](https://docs.rs/orx-concurrent-vec/latest/orx_concurrent_vec/struct.ConcurrentVec.html#method.get_raw)
* [get_raw_mut](https://docs.rs/orx-concurrent-vec/latest/orx_concurrent_vec/struct.ConcurrentVec.html#method.get_raw_mut)

Please let me know if the problem persists with the new version or you encounter a different issue.

Also fyi: Through salsa, through concurrent-vec, an issue about wasm32 compilation was reported in [SplitVec](https://github.com/orxfun/orx-split-vec) crate that ConcurrentVec depends on. The fix is in progress, we can hopefully merge in a few days.

**Comment by nikomatsakis** [comment]
Thanks @orxfun. In the meantime, we switched over to append-only-vec in https://github.com/salsa-rs/salsa/pull/555, it seemed to perform better for our (quite simple) purposes. But we'll be re-evaluating things over time I'm sure.

**Comment by orxfun** [comment]
Actually, I was also curious about the performance after the major revision, your comment reminded me of this waiting task. Benchmarks resurrected, at least the [experiments](https://github.com/orxfun/orx-concurrent-vec?tab=readme-ov-file#benchmarks) in the repo look good, safer but not slower, rust makes me happy. Certainly does not prove anything, benchmarks & results vary in different use cases. Also dived into append-only-vec a little bit, lovely to see similarities & differences.

Closing this issue. Feel free to reach out whenever there is an exciting use case!
